### ISSUE TITLE
Uploaded binary files corrupted

### ISSUE THREAD

**Issue by tomgoren** [vektorlab/slackcat#55]
```
cat prince-charles.jpg | slackcat -c my_favorite_channel -n prince-charles.jpg

```
This works supposedly, but after downloading I get a corrupted file.

![screen shot 2017-12-05 at 2 52 03 pm](https://user-images.githubusercontent.com/806975/33627559-e545bd24-d9cb-11e7-9655-472fcc0dad1f.png)

It even recognizes the file type.

I suspect that this is due to us using [`bufio.ScanLines`](https://github.com/vektorlab/slackcat/blob/50744de5fa6a9b49858eea4892b9a9377c34a764/main.go#L21) but I don't know diddly about Golang.

Thanks!

**Comment by bcicen** [comment]
@tomgoren you are correct that `ScanLines` is the culprit -- since binary files can be directly uploaded when provided as an argument, it was originally assumed that any piped input would be plaintext.

There's no good reason not to read input as bytes in this circumstance though(i.e. if `--stream` mode is not enabled), so this change has been made and is available in the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v1.4)

**Comment by tomgoren** [comment]
Awesome - thanks @bcicen !!! ❤️

**Comment by tomgoren** [comment]
Confirmed - it is fixed!
